### PR TITLE
Appveyor

### PR DESCRIPTION
**Pull request by davidwallis3101**
Added an appveyor build file that can be used to build and push the nuget package automatically.. 

You will need to create an account on appveyor which is free :)

### CODE REVIEW

**Comment by tomidix** [comment]
Hi,

thanks for your commit. I'd just like to ask you if we really do need appveyor for nuget build? 
Nuget is already [available](https://www.nuget.org/packages/Tomidix.CSharpTradFriLibrary/).

Auto Build and nuget publish is configured on Microsoft VS team services already. I can add yml if someone wants to use it but I'm not sure if we need to use as the same thing is already configured on microsoft platform. What do you think? Any special benefit of using it?

**Comment by davidwallis3101** [comment]
no benefit if you already have a build and auto package / push configured - just couldnt tell :) maybe add a badge

**Comment by tomidix** [comment]
Yes, you are right. I turned on badge on vsts build, and I will also add a nuget and dependencies badges... I've decided to keep your work because of the future, maybe something happens (Microsoft had some strange decisions) so CI will be migrated to appveyor.

Can you cancel this pull request and put it to develop branch, because any commit to master will trigger build and obviously I have some more commits to do too.

Thanks and sorry again for missing the badges, will add them soon.

**Comment by davidwallis3101** [comment]
will do in a week as I'm away now

**Pull request closed without merging**
